language: go
os:
  - linux
go:
  - "1.10.x"
  - "1.9"

before_install:
- go get github.com/mitchellh/gox
- go get github.com/inconshreveable/mousetrap
- go get github.com/mattn/goveralls

script:
- go get -t -v ./...
- mkdir data
- curl "https://api.mockaroo.com/api/278745a0?count=500&key=c32fb840" > "Rossy_Table_source.json"
- mv Rossy_Table_source.json ./data
- mv data ./app/database
- go test github.com/yujiahaol68/rossy/app/database
- rm -f ./app/database/db_test.go
- go test -v -race ./...
- $GOPATH/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN
- gox -os="linux darwin windows" -arch="amd64" -output="rossy.{{.OS}}.{{.Arch}}" -verbose ./...
- du -sh * | grep -e "darwin" -e "linux" -e "windows"
